name: Deploy to IPFS

on:
  push:
    branches:
      - shayzluf-patch-1  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build

    - name: Install ipfs-deploy
      run: npm install -g ipfs-deploy

    - name: Deploy to IPFS
      run: ipd build --path-to-deploy=build/ --pinata
      env:
        IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.PINATA_API_KEY }}
        IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
